# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, aligned to sys.path.insert(0, sys.path[0])
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for local time
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow modules to be loaded relative to the
# script_location directory; this is useful for modular layouts
# without installation.
# version_locations = %(here)s/bar:%(here)s/bat

# version path separator; defaults to "os.pathsep".
# Use a space to span multiple lines in select scenarios (#311)
# version_path_separator = :

# set to 'true' to search source files for plugins;
# this is only necessary if plugins are not installed via setuptools
# search_path_for_plugins = false

# the database url is dynamically overridden in env.py,
# but we provide a default here for fallback.
sqlalchemy.url = sqlite:///./sightfill.db

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
